//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientHatem.WCFHatem {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://pragimtech.com/Employee")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFHatem.IWCFHatem")]
    public interface IWCFHatem {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFHatem/GetMessage", ReplyAction="http://tempuri.org/IWCFHatem/GetMessageResponse")]
        string GetMessage(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFHatem/GetMessage", ReplyAction="http://tempuri.org/IWCFHatem/GetMessageResponse")]
        System.Threading.Tasks.Task<string> GetMessageAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFHatem/GetEmployee", ReplyAction="http://tempuri.org/IWCFHatem/GetEmployeeResponse")]
        WebClientHatem.WCFHatem.Employee GetEmployee(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFHatem/GetEmployee", ReplyAction="http://tempuri.org/IWCFHatem/GetEmployeeResponse")]
        System.Threading.Tasks.Task<WebClientHatem.WCFHatem.Employee> GetEmployeeAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFHatem/SaveEmployee", ReplyAction="http://tempuri.org/IWCFHatem/SaveEmployeeResponse")]
        void SaveEmployee(WebClientHatem.WCFHatem.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFHatem/SaveEmployee", ReplyAction="http://tempuri.org/IWCFHatem/SaveEmployeeResponse")]
        System.Threading.Tasks.Task SaveEmployeeAsync(WebClientHatem.WCFHatem.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFHatem/DeleteEmployee", ReplyAction="http://tempuri.org/IWCFHatem/DeleteEmployeeResponse")]
        void DeleteEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFHatem/DeleteEmployee", ReplyAction="http://tempuri.org/IWCFHatem/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task DeleteEmployeeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFHatem/Stam", ReplyAction="http://tempuri.org/IWCFHatem/StamResponse")]
        void Stam();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFHatem/Stam", ReplyAction="http://tempuri.org/IWCFHatem/StamResponse")]
        System.Threading.Tasks.Task StamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFHatem/JsonWow", ReplyAction="http://tempuri.org/IWCFHatem/JsonWowResponse")]
        void JsonWow();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFHatem/JsonWow", ReplyAction="http://tempuri.org/IWCFHatem/JsonWowResponse")]
        System.Threading.Tasks.Task JsonWowAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFHatemChannel : WebClientHatem.WCFHatem.IWCFHatem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFHatemClient : System.ServiceModel.ClientBase<WebClientHatem.WCFHatem.IWCFHatem>, WebClientHatem.WCFHatem.IWCFHatem {
        
        public WCFHatemClient() {
        }
        
        public WCFHatemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFHatemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFHatemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFHatemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMessage(string name) {
            return base.Channel.GetMessage(name);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync(string name) {
            return base.Channel.GetMessageAsync(name);
        }
        
        public WebClientHatem.WCFHatem.Employee GetEmployee(int Id) {
            return base.Channel.GetEmployee(Id);
        }
        
        public System.Threading.Tasks.Task<WebClientHatem.WCFHatem.Employee> GetEmployeeAsync(int Id) {
            return base.Channel.GetEmployeeAsync(Id);
        }
        
        public void SaveEmployee(WebClientHatem.WCFHatem.Employee employee) {
            base.Channel.SaveEmployee(employee);
        }
        
        public System.Threading.Tasks.Task SaveEmployeeAsync(WebClientHatem.WCFHatem.Employee employee) {
            return base.Channel.SaveEmployeeAsync(employee);
        }
        
        public void DeleteEmployee(int id) {
            base.Channel.DeleteEmployee(id);
        }
        
        public System.Threading.Tasks.Task DeleteEmployeeAsync(int id) {
            return base.Channel.DeleteEmployeeAsync(id);
        }
        
        public void Stam() {
            base.Channel.Stam();
        }
        
        public System.Threading.Tasks.Task StamAsync() {
            return base.Channel.StamAsync();
        }
        
        public void JsonWow() {
            base.Channel.JsonWow();
        }
        
        public System.Threading.Tasks.Task JsonWowAsync() {
            return base.Channel.JsonWowAsync();
        }
    }
}
